<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>EBVL.FrontEnd.Logics</RootNamespace>
    <AssemblyName>EBVL.FrontEnd.Logics</AssemblyName>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3</AssemblyVersion>
    <FileVersion>1.0.3</FileVersion>
    <InformationalVersion>1.0.3</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\01.Shared\03.Shared.Dto\03.Shared.Dto.csproj" />
    <ProjectReference Include="..\02.FrontEnd.Services\02.FrontEnd.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Pertamina.Extensions.MediatR" Version="1.0.4" />
    <PackageReference Include="Pertamina.Extensions.RestSharp" Version="1.0.4" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
  </ItemGroup>
</Project>
