using EBVL.BackEnd.Logics.Modules.MasterData.Questionnaires;
using EBVL.Shared.Dto.Modules.MasterData.Questionnaires;

namespace EBVL.BackEnd.WebApi.Modules.MasterData.Questionnaires;

public sealed class QuestionnaireEndpoints : IEndpoint
{
    public RouteHandlerBuilder RegisterTo(WebApplication app)
    {
        // TODO: Restore RequireAuthorization after IdAMan API authentication setup is complete.
        _ = app.MapGet(QuestionnaireRoutes.List, async (ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new GetQuestionnairesQuery(), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.List");
        _ = app.MapGet(QuestionnaireRoutes.Detail, async (Guid questionnaireId, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new GetQuestionnaireQuery(questionnaireId), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.Detail");
        _ = app.MapGet(QuestionnaireRoutes.History, async (Guid seriesId, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new GetQuestionnaireVersionHistoryQuery(seriesId), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.History");
        _ = app.MapGet(QuestionnaireRoutes.Sections, async (Guid questionnaireId, [AsParameters] GetQuestionnaireSectionsRequest request, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new GetQuestionnaireSectionsQuery(questionnaireId) { Page = request.Page, PageSize = request.PageSize, SearchText = request.SearchText, SortField = request.SortField, SortOrder = request.SortOrder }, ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.Sections");
        _ = app.MapGet(QuestionnaireRoutes.Questions, async (Guid questionnaireId, Guid sectionId, [AsParameters] GetQuestionnaireQuestionsRequest request, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new GetQuestionnaireQuestionsQuery(questionnaireId, sectionId) { Page = request.Page, PageSize = request.PageSize, SearchText = request.SearchText, SortField = request.SortField, SortOrder = request.SortOrder }, ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.Questions");
        _ = app.MapGet(QuestionnaireRoutes.QuestionDetail, async (Guid questionnaireId, Guid sectionId, Guid questionId, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new GetQuestionnaireQuestionQuery(questionnaireId, sectionId, questionId), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.QuestionDetail");
        _ = app.MapPost(QuestionnaireRoutes.Draft, async (Guid questionnaireId, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new CreateQuestionnaireDraftCommand(questionnaireId), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.CreateDraft");
        _ = app.MapPost(QuestionnaireRoutes.Publish, async (Guid questionnaireId, PublishQuestionnaireRequest body, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new PublishQuestionnaireCommand(questionnaireId, body.RowVersion), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.Publish");
        _ = app.MapPost(QuestionnaireRoutes.Add, async (AddQuestionnaireRequest body, ISender sender, CancellationToken ct) => Results.Created(QuestionnaireRoutes.List, (object?)await sender.Send(new AddQuestionnaireCommand { Code = body.Code, BusinessProcess = body.BusinessProcess, IsActive = body.IsActive }, ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.Add");
        _ = app.MapPost(QuestionnaireRoutes.Sections, async (Guid questionnaireId, AddQuestionnaireSectionRequest body, ISender sender, CancellationToken ct) => Results.Created(QuestionnaireRoutes.Detail, (object?)await sender.Send(new AddQuestionnaireSectionCommand(questionnaireId, body), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.AddSection");
        _ = app.MapPost(QuestionnaireRoutes.AddQuestion, async (Guid questionnaireId, Guid sectionId, AddQuestionnaireQuestionRequest body, ISender sender, CancellationToken ct) => Results.Created(QuestionnaireRoutes.Detail, (object?)await sender.Send(new AddQuestionnaireQuestionCommand(questionnaireId, sectionId, body), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.AddQuestion");
        _ = app.MapPut(QuestionnaireRoutes.UpdateSection, async (Guid questionnaireId, Guid sectionId, UpdateQuestionnaireSectionRequest body, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new UpdateQuestionnaireSectionCommand(questionnaireId, sectionId, body), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.UpdateSection");
        _ = app.MapDelete(QuestionnaireRoutes.UpdateSection, async (Guid questionnaireId, Guid sectionId, [AsParameters] DeleteQuestionnaireChildRequest body, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new DeleteQuestionnaireSectionCommand(questionnaireId, sectionId, body.RowVersion), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.DeleteSection");
        _ = app.MapPut(QuestionnaireRoutes.QuestionDetail, async (Guid questionnaireId, Guid sectionId, Guid questionId, UpdateQuestionnaireQuestionRequest body, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new UpdateQuestionnaireQuestionCommand(questionnaireId, sectionId, questionId, body), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.UpdateQuestion");
        _ = app.MapDelete(QuestionnaireRoutes.QuestionDetail, async (Guid questionnaireId, Guid sectionId, Guid questionId, [AsParameters] DeleteQuestionnaireChildRequest body, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new DeleteQuestionnaireQuestionCommand(questionnaireId, sectionId, questionId, body.RowVersion), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.DeleteQuestion");
        return app.MapPut(QuestionnaireRoutes.Update, async (Guid questionnaireId, UpdateQuestionnaireRequest body, ISender sender, CancellationToken ct) => Results.Ok(await sender.Send(new UpdateQuestionnaireCommand(questionnaireId, body), ct))).AllowAnonymous().WithTags(RouteConfig.Tag).WithName("Questionnaires.Update");
    }
}
