global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Pertamina.Common.Exceptions;
global using Pertamina.Common.Validators;
global using Pertamina.Extensions.DisplayText;
global using Pertamina.Extensions.DisplayText.Statics;
global using Pertamina.Extensions.Text;
global using Pertamina.Services.Authorization.Attributes;
global using Pertamina.Services.DateAndTime;
global using EBVL.BackEnd.Domain.Entities;
global using EBVL.BackEnd.Logics.Common.Extensions;
global using EBVL.BackEnd.Services.Database;
global using EBVL.Shared.Enums;
global using ApiCallsDisplayTextFor = EBVL.Shared.Statics.ApiCalls.DisplayTextFor;
global using AuditsDisplayTextFor = EBVL.Shared.Statics.Audits.DisplayTextFor;
global using CommonDisplayTextFor = Pertamina.Common.Statics.DisplayTextFor;
global using ConfigurationsDisplayTextFor = EBVL.Shared.Statics.Configurations.DisplayTextFor;
global using CountriesDisplayTextFor = EBVL.Shared.Statics.Countries.DisplayTextFor;
global using DocumentsDisplayTextFor = EBVL.Shared.Statics.Documents.DisplayTextFor;
global using DocumentsValueFor = EBVL.Shared.Statics.Documents.ValueFor;
global using UsersDisplayTextFor = EBVL.Shared.Statics.Users.DisplayTextFor;
