global using EBVL.BackEnd.Domain.Entities;
global using EBVL.BackEnd.Logics.Common.Extensions;
global using EBVL.BackEnd.Services.Database;
global using EBVL.Shared.Enums;
global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Pertamina.Common.Exceptions;
global using Pertamina.Common.Validators;
global using Pertamina.Extensions.DisplayText;
global using Pertamina.Extensions.DisplayText.Statics;
global using Pertamina.Extensions.Text;
global using Pertamina.Services.Authorization.Attributes;
global using Pertamina.Services.DateAndTime;
global using ApiCallsDisplayTextFor = EBVL.Shared.Statics.ApiCalls.DisplayTextFor;
global using AuditsDisplayTextFor = EBVL.Shared.Statics.Audits.DisplayTextFor;
global using CommonActionFor = EBVL.Shared.Statics.Common.ActionFor;
global using CommonDisplayTextFor = Pertamina.Common.Statics.DisplayTextFor;
global using CommonModuleFor = EBVL.Shared.Statics.Common.ModuleFor;
global using ConfigurationsDisplayTextFor = EBVL.Shared.Statics.Configurations.DisplayTextFor;
global using CountriesDisplayTextFor = EBVL.Shared.Statics.Countries.DisplayTextFor;
global using DocumentsDisplayTextFor = EBVL.Shared.Statics.Documents.DisplayTextFor;
global using DocumentsValueFor = EBVL.Shared.Statics.Documents.ValueFor;
global using EmailTemplatesDisplayTextFor = EBVL.Shared.Statics.EmailTemplates.DisplayTextFor;
global using EmailTemplatesEmailWith = EBVL.Shared.Statics.EmailTemplates.EmailWith;
global using FileStoragesDisplayTextFor = EBVL.Shared.Statics.FileStorages.DisplayTextFor;
global using FileStoragesResourceFor = EBVL.Shared.Statics.FileStorages.ResourceFor;
global using LendersDisplayTextFor = EBVL.Shared.Statics.Lenders.DisplayTextFor;
global using ProjectLenderReqsDisplayTextFor = EBVL.Shared.Statics.ProjectLenderReqs.DisplayTextFor;
global using ProjectLendersDisplayTextFor = EBVL.Shared.Statics.ProjectLenders.DisplayTextFor;
global using ProjectsDisplayTextFor = EBVL.Shared.Statics.Projects.DisplayTextFor;
global using ProjectStagesDisplayTextFor = EBVL.Shared.Statics.ProjectStages.DisplayTextFor;
global using ProjectFilesDisplayTextFor = EBVL.Shared.Statics.ProjectFiles.DisplayTextFor;
global using StatusesStatusCodeFor = EBVL.Shared.Statics.Statuses.CodeFor;
global using StatusesTableFor = EBVL.Shared.Statics.Statuses.TableFor;
global using UsersDisplayTextFor = EBVL.Shared.Statics.Users.DisplayTextFor;
global using LogTransactionsDisplayTextFor = EBVL.Shared.Statics.LogTransactions.DisplayTextFor;
global using LogEmailsDisplayTextFor = EBVL.Shared.Statics.LogEmails.DisplayTextFor;
