global using EBVL.BackEnd.Domain.Entities;
global using EBVL.BackEnd.Infrastructure.Database.InitialData;
global using EBVL.BackEnd.Services.Database;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Pertamina.Common.Exceptions;
global using Pertamina.Services.Database.Common.Extensions;
global using Pertamina.Services.Database.Common.Statics;
global using ApiCallsMaximumLengthFor = EBVL.Shared.Statics.ApiCalls.MaximumLengthFor;
global using AuditsMaximumLengthFor = EBVL.Shared.Statics.Audits.MaximumLengthFor;
global using CommonActionFor = EBVL.Shared.Statics.Common.ActionFor;
global using CommonMaximumLengthFor = Pertamina.Common.Statics.MaximumLengthFor;
global using CommonModuleFor = EBVL.Shared.Statics.Common.ModuleFor;
global using ConfigurationsMaximumLengthFor = EBVL.Shared.Statics.Configurations.MaximumLengthFor;
global using CountriesMaximumLengthFor = EBVL.Shared.Statics.Countries.MaximumLengthFor;
global using DocumentsMaximumLengthFor = EBVL.Shared.Statics.Documents.MaximumLengthFor;
global using EmailTemplatesEmailWith = EBVL.Shared.Statics.EmailTemplates.EmailWith;
global using EmailTemplatesMaximumLengthFor = EBVL.Shared.Statics.EmailTemplates.MaximumLengthFor;
global using ExternalLoginLogsMaximumLengthFor = EBVL.Shared.Statics.ExternalLoginLogs.MaximumLengthFor;
global using FileStoragesMaximumLengthFor = EBVL.Shared.Statics.FileStorages.MaximumLengthFor;
global using LendersMaximumLengthFor = EBVL.Shared.Statics.Lenders.MaximumLengthFor;
global using LogEmailsMaximumLengthFor = EBVL.Shared.Statics.LogEmails.MaximumLengthFor;
global using LogTransactionsMaximumLengthFor = EBVL.Shared.Statics.LogTransactions.MaximumLengthFor;
global using ProjectAttachmentsMaximumLengthFor = EBVL.Shared.Statics.ProjectAttachments.MaximumLengthFor;
global using ProjectLendersMaximumLengthFor = EBVL.Shared.Statics.ProjectLenders.MaximumLengthFor;
global using ProjectReqsMaximumLengthFor = EBVL.Shared.Statics.ProjectReqs.MaximumLengthFor;
global using ProjectsMaximumLengthFor = EBVL.Shared.Statics.Projects.MaximumLengthFor;
global using ProjectStagesMaximumLengthFor = EBVL.Shared.Statics.ProjectStages.MaximumLengthFor;
global using PublicHolidaysMaximumLengthFor = EBVL.Shared.Statics.PublicHolidays.MaximumLengthFor;
global using StatusesMaximumLengthFor = EBVL.Shared.Statics.Statuses.MaximumLengthFor;
global using UsersMaximumLengthFor = EBVL.Shared.Statics.Users.MaximumLengthFor;
