global using Microsoft.AspNetCore.Builder;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Pertamina.Common.Exceptions;
global using Pertamina.Services.Database.Common.Extensions;
global using Pertamina.Services.Database.Common.Statics;
global using EBVL.BackEnd.Domain.Entities;
global using EBVL.BackEnd.Infrastructure.Database.InitialData;
global using EBVL.BackEnd.Services.Database;
global using ApiCallsMaximumLengthFor = EBVL.Shared.Statics.ApiCalls.MaximumLengthFor;
global using AuditsMaximumLengthFor = EBVL.Shared.Statics.Audits.MaximumLengthFor;
global using CommonMaximumLengthFor = Pertamina.Common.Statics.MaximumLengthFor;
global using ConfigurationsMaximumLengthFor = EBVL.Shared.Statics.Configurations.MaximumLengthFor;
global using CountriesMaximumLengthFor = EBVL.Shared.Statics.Countries.MaximumLengthFor;
global using DocumentsMaximumLengthFor = EBVL.Shared.Statics.Documents.MaximumLengthFor;
global using PublicHolidaysMaximumLengthFor = EBVL.Shared.Statics.PublicHolidays.MaximumLengthFor;
global using UsersMaximumLengthFor = EBVL.Shared.Statics.Users.MaximumLengthFor;
global using VendorsMaximumLengthFor = EBVL.Shared.Statics.Vendors.MaximumLengthFor;
