global using FluentValidation;
global using EBVL.Shared.Enums;
global using Pertamina.Common.Dto.Requests;
global using Pertamina.Common.Dto.Responses;
global using Pertamina.Common.Validators;
global using Pertamina.Common.Validators.Extensions;
global using ApiCallsDisplayTextFor = EBVL.Shared.Statics.ApiCalls.DisplayTextFor;
global using AuditsDisplayTextFor = EBVL.Shared.Statics.Audits.DisplayTextFor;
global using CommonDisplayTextFor = Pertamina.Common.Statics.DisplayTextFor;
global using CommonMaximumLengthFor = Pertamina.Common.Statics.MaximumLengthFor;
global using CommonMinimumLengthFor = Pertamina.Common.Statics.MinimumLengthFor;
global using ConfigurationsDisplayTextFor = EBVL.Shared.Statics.Configurations.DisplayTextFor;
global using ConfigurationsMaximumLengthFor = EBVL.Shared.Statics.Configurations.MaximumLengthFor;
global using ConfigurationsMinimumLengthFor = EBVL.Shared.Statics.Configurations.MinimumLengthFor;
global using CountriesDisplayTextFor = EBVL.Shared.Statics.Countries.DisplayTextFor;
global using CountriesMaximumLengthFor = EBVL.Shared.Statics.Countries.MaximumLengthFor;
global using CountriesMinimumLengthFor = EBVL.Shared.Statics.Countries.MinimumLengthFor;
global using DocumentsDisplayTextFor = EBVL.Shared.Statics.Documents.DisplayTextFor;
global using DocumentsMaximumLengthFor = EBVL.Shared.Statics.Documents.MaximumLengthFor;
global using DocumentsMinimumLengthFor = EBVL.Shared.Statics.Documents.MinimumLengthFor;
global using PublicHolidaysDisplayTextFor = EBVL.Shared.Statics.PublicHolidays.DisplayTextFor;
global using PublicHolidaysMinimumValueFor = EBVL.Shared.Statics.PublicHolidays.MinimumValueFor;
global using UsersDisplayTextFor = EBVL.Shared.Statics.Users.DisplayTextFor;
global using UsersMaximumLengthFor = EBVL.Shared.Statics.Users.MaximumLengthFor;
global using UsersMinimumLengthFor = EBVL.Shared.Statics.Users.MinimumLengthFor;
