global using FluentValidation;
global using Pertamina.Common.Dto.Requests;
global using Pertamina.Common.Dto.Responses;
global using Pertamina.Common.Validators;
global using Pertamina.Common.Validators.Extensions;
global using ApiCallsDisplayTextFor = EBVL.Shared.Statics.ApiCalls.DisplayTextFor;
global using AuditsDisplayTextFor = EBVL.Shared.Statics.Audits.DisplayTextFor;
global using CommonDisplayTextFor = Pertamina.Common.Statics.DisplayTextFor;
global using CommonMaximumLengthFor = Pertamina.Common.Statics.MaximumLengthFor;
global using CommonMinimumLengthFor = Pertamina.Common.Statics.MinimumLengthFor;
global using ConfigurationsDisplayTextFor = EBVL.Shared.Statics.Configurations.DisplayTextFor;
global using ConfigurationsMaximumLengthFor = EBVL.Shared.Statics.Configurations.MaximumLengthFor;
global using ConfigurationsMinimumLengthFor = EBVL.Shared.Statics.Configurations.MinimumLengthFor;
global using CountriesDisplayTextFor = EBVL.Shared.Statics.Countries.DisplayTextFor;
global using CountriesMaximumLengthFor = EBVL.Shared.Statics.Countries.MaximumLengthFor;
global using CountriesMinimumLengthFor = EBVL.Shared.Statics.Countries.MinimumLengthFor;
global using DocumentsDisplayTextFor = EBVL.Shared.Statics.Documents.DisplayTextFor;
global using DocumentsMaximumLengthFor = EBVL.Shared.Statics.Documents.MaximumLengthFor;
global using DocumentsMinimumLengthFor = EBVL.Shared.Statics.Documents.MinimumLengthFor;
global using EmailTemplatesDisplayTextFor = EBVL.Shared.Statics.EmailTemplates.DisplayTextFor;
global using EmailTemplatesMaximumLengthFor = EBVL.Shared.Statics.EmailTemplates.MaximumLengthFor;
global using EmailTemplatesMinimumLengthFor = EBVL.Shared.Statics.EmailTemplates.MinimumLengthFor;
global using FileStoragesDisplayTextFor = EBVL.Shared.Statics.FileStorages.DisplayTextFor;
global using LendersDisplayTextFor = EBVL.Shared.Statics.Lenders.DisplayTextFor;
global using LendersMaximumLengthFor = EBVL.Shared.Statics.Lenders.MaximumLengthFor;
global using LendersMinimumLengthFor = EBVL.Shared.Statics.Lenders.MinimumLengthFor;
global using LogEmailsDisplayTextFor = EBVL.Shared.Statics.LogEmails.DisplayTextFor;
global using LogTransactionsDisplayTextFor = EBVL.Shared.Statics.LogTransactions.DisplayTextFor;
global using ProjectAttachmentsMaximumLengthFor = EBVL.Shared.Statics.ProjectAttachments.MaximumLengthFor;
global using ProjectAttachmentsMinimumLengthFor = EBVL.Shared.Statics.ProjectAttachments.MinimumLengthFor;
global using ProjectReqsMaximumLengthFor = EBVL.Shared.Statics.ProjectReqs.MaximumLengthFor;
global using ProjectReqsMinimumLengthFor = EBVL.Shared.Statics.ProjectReqs.MinimumLengthFor;
global using ProjectsDisplayTextFor = EBVL.Shared.Statics.Projects.DisplayTextFor;
global using ProjectsMaximumLengthFor = EBVL.Shared.Statics.Projects.MaximumLengthFor;
global using ProjectsMinimumLengthFor = EBVL.Shared.Statics.Projects.MinimumLengthFor;
global using ProjectStagesDisplayTextFor = EBVL.Shared.Statics.ProjectStages.DisplayTextFor;
global using ProjectStagesMaximumLengthFor = EBVL.Shared.Statics.ProjectStages.MaximumLengthFor;
global using ProjectStagesMinimumLengthFor = EBVL.Shared.Statics.ProjectStages.MinimumLengthFor;
global using PublicHolidaysDisplayTextFor = EBVL.Shared.Statics.PublicHolidays.DisplayTextFor;
global using PublicHolidaysMinimumValueFor = EBVL.Shared.Statics.PublicHolidays.MinimumValueFor;
global using StatusesCodeFor = EBVL.Shared.Statics.Statuses.CodeFor;
global using StatusesDisplayTextFor = EBVL.Shared.Statics.Statuses.DisplayTextFor;
global using UsersDisplayTextFor = EBVL.Shared.Statics.Users.DisplayTextFor;
global using UsersMaximumLengthFor = EBVL.Shared.Statics.Users.MaximumLengthFor;
global using UsersMinimumLengthFor = EBVL.Shared.Statics.Users.MinimumLengthFor;
global using VendorRegistrationsMaximumLengthFor = EBVL.Shared.Statics.VendorRegistrations.MaximumLengthFor;
