<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>EBVL.Shared.Enums</RootNamespace>
    <AssemblyName>EBVL.Shared.Enums</AssemblyName>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3</AssemblyVersion>
    <FileVersion>1.0.3</FileVersion>
    <InformationalVersion>1.0.3</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pertamina.Common.Attributes" Version="1.0.4" />
  </ItemGroup>
</Project>
