<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>EBVL.FrontEnd.WebUi</RootNamespace>
    <AssemblyName>EBVL.FrontEnd.WebUi</AssemblyName>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3</AssemblyVersion>
    <FileVersion>1.0.3</FileVersion>
    <InformationalVersion>1.0.3</InformationalVersion>
    <!-- for enable docker
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    -->
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\03.FrontEnd.Infrastructure\03.FrontEnd.Infrastructure.csproj" />
    <ProjectReference Include="..\04.FrontEnd.Logics\04.FrontEnd.Logics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Pertamina.Common.Components" Version="1.0.4" />
    <PackageReference Include="Pertamina.Extensions.DisplayText" Version="1.0.4" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="7.0.0" />
    <PackageReference Include="Bogus" Version="35.6.5" />
  </ItemGroup>
</Project>
