global using EBVL.FrontEnd.Infrastructure.AppConfigFrontEnd;
global using EBVL.FrontEnd.Services.AppConfigFrontEnd;
global using EBVL.FrontEnd.WebUi.Common.Extensions;
global using EBVL.FrontEnd.WebUi.Common.Statics;
global using EBVL.Shared.Enums;
global using FluentValidation;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.Extensions.Options;
global using MudBlazor;
global using Pertamina.Common.Exceptions;
global using Pertamina.Common.Validators;
global using Pertamina.Extensions.DisplayText;
global using Pertamina.Extensions.DisplayText.Statics;
global using Pertamina.Extensions.Identity;
global using Pertamina.Extensions.Size;
global using AdministrationApiCallsBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Administration.Features.ApiCalls.Statics.BreadcrumbFor;
global using AdministrationApiCallsRouteFor = EBVL.FrontEnd.WebUi.Modules.Administration.Features.ApiCalls.Statics.RouteFor;
global using AdministrationAuditsBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Administration.Features.Audits.Statics.BreadcrumbFor;
global using AdministrationAuditsRouteFor = EBVL.FrontEnd.WebUi.Modules.Administration.Features.Audits.Statics.RouteFor;
global using AdministrationBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Administration.Statics.BreadcrumbFor;
global using AdministrationConfigurationsBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Administration.Features.Configurations.Statics.BreadcrumbFor;
global using AdministrationConfigurationsRouteFor = EBVL.FrontEnd.WebUi.Modules.Administration.Features.Configurations.Statics.RouteFor;
global using AdministrationDisplayTextFor = EBVL.FrontEnd.WebUi.Modules.Administration.Statics.DisplayTextFor;
global using AdministrationPermissions = EBVL.Shared.Dto.Modules.Administration.Permissions;
global using AdministrationRouteFor = EBVL.FrontEnd.WebUi.Modules.Administration.Statics.RouteFor;
global using ApiCallsDisplayTextFor = EBVL.Shared.Statics.ApiCalls.DisplayTextFor;
global using AuditsDisplayTextFor = EBVL.Shared.Statics.Audits.DisplayTextFor;
global using AuthenticationRouteFor = EBVL.FrontEnd.Infrastructure.Authentication.Statics.RouteFor;
global using AuthenticationTypeFor = EBVL.FrontEnd.Infrastructure.Authentication.Statics.AuthenticationTypeFor;
global using CommonBreadcrumbFor = EBVL.FrontEnd.WebUi.Common.Statics.BreadcrumbFor;
global using CommonDefaultValueFor = Pertamina.Common.Statics.DefaultValueFor;
global using CommonDisplayTextFor = Pertamina.Common.Statics.DisplayTextFor;
global using ConfigurationsDisplayTextFor = EBVL.Shared.Statics.Configurations.DisplayTextFor;
global using CountriesDisplayTextFor = EBVL.Shared.Statics.Countries.DisplayTextFor;
global using DocumentsDisplayTextFor = EBVL.Shared.Statics.Documents.DisplayTextFor;
global using DocumentsMaximumValueFor = EBVL.Shared.Statics.Documents.MaximumValueFor;
global using ExamplesBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Examples.Statics.BreadcrumbFor;
global using ExamplesDisplayTextFor = EBVL.FrontEnd.WebUi.Modules.Examples.Statics.DisplayTextFor;
global using ExamplesDocumentsBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Documents.Statics.BreadcrumbFor;
global using ExamplesDocumentsRouteFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Documents.Statics.RouteFor;
global using ExamplesDummiesDisplayTextFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Dummies.Statics.DisplayTextFor;
global using ExamplesDummiesRouteFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Dummies.Statics.RouteFor;
global using ExamplesEmailsBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Emails.Statics.BreadcrumbFor;
global using ExamplesEmailsDisplayTextFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Emails.Statics.DisplayTextFor;
global using ExamplesEmailsRouteFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Emails.Statics.RouteFor;
global using ExamplesLoadingsBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Loadings.Statics.BreadcrumbFor;
global using ExamplesLoadingsDisplayTextFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Loadings.Statics.DisplayTextFor;
global using ExamplesLoadingsRouteFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.Loadings.Statics.RouteFor;
global using ExamplesPublicHolidaysBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.PublicHolidays.Statics.BreadcrumbFor;
global using ExamplesPublicHolidaysRouteFor = EBVL.FrontEnd.WebUi.Modules.Examples.Features.PublicHolidays.Statics.RouteFor;
global using ExamplesRouteFor = EBVL.FrontEnd.WebUi.Modules.Examples.Statics.RouteFor;
global using LendersDisplayTextFor = EBVL.Shared.Statics.Lenders.DisplayTextFor;
global using MainBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Main.Statics.BreadcrumbFor;
global using MainDisplayTextFor = EBVL.FrontEnd.WebUi.Modules.Main.Statics.DisplayTextFor;
global using VendorMonitoringRegistrationVendorsRouteFor = EBVL.FrontEnd.WebUi.Modules.Main.Features.VendorMonitoring.RegistrationVendors.Statics.RouteFor;
global using VendorMonitoringRegistrationVendorsBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.Main.Features.VendorMonitoring.RegistrationVendors.Statics.BreadcrumbFor;
global using VendorMonitoringRegistrationVendorsDisplayTextFor = EBVL.FrontEnd.WebUi.Modules.Main.Features.VendorMonitoring.RegistrationVendors.Statics.DisplayTextFor;
global using MainPermissions = EBVL.Shared.Dto.Modules.Main.Permissions;
global using MainRouteFor = EBVL.FrontEnd.WebUi.Modules.Main.Statics.RouteFor;
global using PublicHolidaysDisplayTextFor = EBVL.Shared.Statics.PublicHolidays.DisplayTextFor;
global using UsersDisplayTextFor = EBVL.Shared.Statics.Users.DisplayTextFor;
global using WebUiDisplayTextFor = EBVL.FrontEnd.WebUi.Common.Statics.DisplayTextFor;
global using MasterDataRouteFor = EBVL.FrontEnd.WebUi.Modules.MasterData.Statics.RouteFor;
global using MasterDataBreadcrumbFor = EBVL.FrontEnd.WebUi.Modules.MasterData.Statics.BreadcrumbFor;
global using QuestionnaireRouteFor = EBVL.FrontEnd.WebUi.Modules.MasterData.Features.Questionnaires.Statics.RouteFor;
