global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Pertamina.Common.Exceptions;
global using AdministrationPermissions = EBVL.Shared.Dto.Modules.Administration.Permissions;
global using MainPermissions = EBVL.Shared.Dto.Modules.Main.Permissions;
global using MasterDataPermissions = EBVL.Shared.Dto.Modules.MasterData.Permissions;
